# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'RNOpencv3' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for RNOpencv3
  pod 'OpenCV', '~> 3.4.3'
end
